### PR TITLE
Core update to the 20210130 release.

### PR DESCRIPTION
**Pull request by rampa069**

### CODE REVIEW

**Comment by Kitrinx** [comment]
This is quite an update. I see that you forked off of my own branch rather than the MiSTer_devel branch. Can you break down for me what you have going on here?

**Comment by Kitrinx** [comment]
I will get sys up to date, so I will remove your release for now. The framework is actually quite old on this.

**Comment by rampa069** [comment]
hi,  yes, i saw the old framework, but dont wanted to touch this in the pull request...  if you prefer, i can pull the mister-devel , update the framework and make the pull request to this repo.

there are a lot of bugfixes/new features.

Updated T48 core
Bugfixes to i8244
new cartridge formats.
The voice 

and some more.

**Comment by Kitrinx** [comment]
I am working on updating sys now and cleaning up the directory structure and some warnings, and then I will push to mister_devel. In the future it's best to fork off of that.

**Comment by Kitrinx** [comment]
Very nice additions by the way, thank you for working on this!

**Comment by rampa069** [comment]
ok, we wrote at the same time, ok. i'll wait and fork mister-devel.

**Comment by Kitrinx** [comment]
I noticed audio and video is strange in Tutankham in Odyssey2 mode, is this a videopac only game?

**Comment by rampa069** [comment]
yes, the only bin i have of it is a EU and is clasified as "proto"

**Comment by rampa069** [comment]
[ntsc_tutankham.zip](https://github.com/Kitrinx/Odyssey2_MiSTer/files/5901160/ntsc_tutankham.zip)
found this version!

**Comment by Kitrinx** [comment]
I found that one as well after I asked, it seems to run better, but it seems like the audio has an odd warbling effect. I've been working on two things: trying to get the vsync in a more correct place, and also trying to implement an adjustable pll, although i'm struggling to get the parameters right for the adjustable pll. I'm also trying to figure out what is causing that flicker on the left side of the screen in games like Atlantis. You can check the sys_update branch in my repo for updated framework.

**Comment by rampa069** [comment]
I have the audio issue fixed. Another difference in the 8244 datasheet.

**Comment by Kitrinx** [comment]
I have invited you to to the mister-devel repo to manage. You may submit any changes there now and manage yourself, since this core is mostly yours now :)

You can do a release when you feel everything is correct.

**Pull request merged**
